services:
  dashboard:
    container_name: dashboard
    image: hummingbot/dashboard:latest
    #port 8501
    environment:
      - AUTH_SYSTEM_ENABLED=False
      - BACKEND_API_HOST=hummingbot-api
      - BACKEND_API_PORT=8000
    volumes:
      - ./pages:/home/dashboard/frontend/pages
  hummingbot-api:
    container_name: hummingbot-api
    image: hummingbot/hummingbot-api:latest
    # port 8000
    volumes:
      - ./bots:/hummingbot-api/bots
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Override specific values for Docker networking
      - BROKER_HOST=emqx
      - DATABASE_URL=${DATABASE_URL}
      #postgresql+asyncpg://hbot:hummingbot-api@postgres:5432/hummingbot_api
    #depends_on:
    #  - postgres
  emqx:
    container_name: hummingbot-broker
    image: emqx:5
    restart: unless-stopped
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=emqx
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=[emqx@emqx]
      - EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
      - emqx-etc:/opt/emqx/etc
    # ports:
    #   - "1883:1883" # mqtt:tcp
    #   - "8883:8883" # mqtt:tcp:ssl
    #   - "8083:8083" # mqtt:ws
    #   - "8084:8084" # mqtt:ws:ssl
    #   - "8081:8081" # http:management
    #   - "18083:18083" # http:dashboard
    #   - "61613:61613" # web-stomp gateway
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
  oauth2-proxy-dashboard:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    environment:
      - OAUTH2_PROXY_PROVIDER=github # Change to your provider
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH_COOKIE_SECRET}
      - OAUTH2_PROXY_GITHUB_USERS=${OAUTH_GITHUB_USERS}
      - OAUTH2_PROXY_UPSTREAMS=http://dashboard:8501
      - OAUTH2_PROXY_REDIRECT_URL=${SERVICE_URL_OAUTH2_PROXY_DASHBOARD/oauth2/callback}
      - OAUTH2_PROXY_HTTP_ADDR=0.0.0.0:8080
    #ports:
    #  - "8080:8080"
    depends_on:
      - dashboard
  oauth2-proxy-api:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    environment:
      - OAUTH2_PROXY_PROVIDER=github # Change to your provider
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH_COOKIE_SECRET}
      - OAUTH2_PROXY_GITHUB_USERS=${OAUTH_GITHUB_USERS}
      - OAUTH2_PROXY_UPSTREAMS=http://hummingbot-api:8000
      - OAUTH2_PROXY_REDIRECT_URL=${SERVICE_URL_OAUTH2_PROXY_API/oauth2/callback}
      - OAUTH2_PROXY_HTTP_ADDR=0.0.0.0:8080
    #ports:
    #  - "8080:8080"
    depends_on:
      - hummingbot-api
  #postgres:
  #  container_name: hummingbot-postgres
  #  image: postgres:15
  #  restart: unless-stopped
  #  environment:
  #    - POSTGRES_DB=hummingbot_api
  #    - POSTGRES_USER=hbot
  #    - POSTGRES_PASSWORD=hummingbot-api
  #  volumes:
  #    - postgres-data:/var/lib/postgresql/data
  #  ports:
  #    - "5432:5432"
  #  networks:
  #    - emqx-bridge
  #  healthcheck:
  #    test: ["CMD-SHELL", "pg_isready -U hbot -d hummingbot_api"]
  #    interval: 10s
  #    timeout: 5s
  #    retries: 5
